### ISSUE TITLE
How to Select pileup_mode ?

### ISSUE THREAD

**Issue by hmyh1202** [PacificBiosciences/pb-CpG-tools#18]
Hello:

    In your script of aligned_bam_to_cpg_scores.py the parameter --pileup_mode has 2 selection, which the cunt is the default parameter. 
    I have test the --pileup_mode model  but some errors were report like that below when I use multiple thread, however only use 1 thread did not report the error:
Chunking regions for multiprocessing.
Running multiprocessing on 6,189 chunks.
  0%|                                                                                            | 0/6189 [00:19<?, ?it/s]
2022-06-20 16:53:31.124000: F tensorflow/core/platform/default/env.cc:73] Check failed: ret == 0 (11 vs. 0)Thread tf_Compute creation via pthread_create() failed.
2022-06-20 16:53:31.124055: F tensorflow/core/platform/default/env.cc:73] Check failed: ret == 0 (11 vs. 0)Thread tf_Compute creation via pthread_create() failed.
2022-06-20 16:53:31.124571: F tensorflow/core/platform/default/env.cc:73] Check failed: ret == 0 (11 vs. 0)Thread tf_Compute creation via pthread_create() failed.
2022-06-20 16:53:31.124822: F tensorflow/core/platform/default/env.cc:73] Check failed: ret == 0 (11 vs. 0)Thread tf_Compute creation via pthread_create() failed.
Exception in thread Thread-4:
  0%|                                                                                            | 0/6189 [05:35<?, ?it/s]Traceback (most recent call last):
  File "anaconda3/envs/cpg/lib/python3.9/threading.py", line 973, in _bootstrap_inner

    self.run()
  File "anaconda3/envs/cpg/lib/python3.9/concurrent/futures/process.py", line 320, in run
    self.terminate_broken(cause)
  File "anaconda3/envs/cpg/lib/python3.9/concurrent/futures/process.py", line 455, in terminate_broken
    work_item.future.set_exception(bpe)
  File "naconda3/envs/cpg/lib/python3.9/concurrent/futures/_base.py", line 549, in set_exception
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
concurrent.futures._base.InvalidStateError: CANCELLED: <Future at 0x7fbba15c5d30 state=cancelled>
Traceback (most recent call last):
  File "anaconda3/envs/pb_CpG_tools/aligned_bam_to_cpg_scores.py", line 981, in <module>
    main()
  File "anaconda3/envs/pb_CpG_tools/aligned_bam_to_cpg_scores.py", line 970, in main
    bed_results = run_all_pileup_processing(regions_to_process, args.threads)
  File "anaconda3/envs/pb_CpG_tools/aligned_bam_to_cpg_scores.py", line 758, in run_all_pileup_processing
    bed_results = process_map(run_process_region, regions_to_process, max_workers=threads, miniters=threads, chunksize=1, smoothing=0)
  File "anaconda3/envs/cpg/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 130, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "anaconda3/envs/cpg/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "anaconda3/envs/cpg/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "anaconda3/envs/cpg/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "anaconda3/envs/cpg/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "anaconda3/envs/cpg/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "anaconda3/envs/cpg/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

After install cloud-tpu-client  also 

The Best !

**Comment by dportik** [comment]
@hmyh1202 can you confirm which versions of the dependencies you have installed? Many errors with tensorflow result from incompatibilities between python and package versions.

```
 python = ?
 tensorflow = ?
 numpy = ? 
```
