### ISSUE TITLE
error installing pb-CpG-tools 

### ISSUE THREAD

**Issue by Mjaraespejo** [PacificBiosciences/pb-CpG-tools#34]
Hello,
I am trying to install the tools using the command: conda env create -f conda_env_cpg.yaml.
But I am getting this error.
 ```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 89, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 106, in get_single_data
        node = self.composer.get_single_node()
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/drives/ssd1/manuel/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 29, column 66:
         ... le" content="{&quot;groups&quot;: [], &quot;environmentKey&quot; ... 
                                             ^ (line: 29)

`$ /drives/ssd1/manuel/miniconda3/bin/conda-env create -f conda_env_cpg.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
   CONDA_BACKUP_ADDR2LINE=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-addr2line
          CONDA_BACKUP_AR=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-ar
          CONDA_BACKUP_AS=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-as
       CONDA_BACKUP_BUILD=x86_64-conda-linux-gnu
          CONDA_BACKUP_CC=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-cc
CONDA_BACKUP_CC_FOR_BUILD=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-cc
      CONDA_BACKUP_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
CONDA_BACKUP_CMAKE_PREFIX_PATH=/drives/ssd1/manuel/miniconda3/envs/r4-base:/drives/ssd1/manuel/minico
                          nda3/envs/r4-base/x86_64-conda-linux-gnu/sysroot/usr
CONDA_BACKUP_CONDA_BUILD_SYSROOT=/drives/ssd1/manuel/miniconda3/envs/r4-base/x86_64-conda-linux-
                          gnu/sysroot
         CONDA_BACKUP_CPP=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-cpp
    CONDA_BACKUP_CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
         CONDA_BACKUP_CXX=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-c++
     CONDA_BACKUP_CXXFILT=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-c++filt
    CONDA_BACKUP_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0
                          -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
CONDA_BACKUP_CXX_FOR_BUILD=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-c++
CONDA_BACKUP_DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
CONDA_BACKUP_DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
CONDA_BACKUP_DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0
                          -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
CONDA_BACKUP_DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
CONDA_BACKUP_DEBUG_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
     CONDA_BACKUP_ELFEDIT=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-elfedit
         CONDA_BACKUP_F77=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gfortran
         CONDA_BACKUP_F90=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gfortran
         CONDA_BACKUP_F95=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-f95
          CONDA_BACKUP_FC=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gfortran
      CONDA_BACKUP_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
CONDA_BACKUP_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /drives/ssd1/manuel/miniconda3/envs/r4-base/include
         CONDA_BACKUP_GCC=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gcc
      CONDA_BACKUP_GCC_AR=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gcc-ar
      CONDA_BACKUP_GCC_NM=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gcc-nm
  CONDA_BACKUP_GCC_RANLIB=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gcc-ranlib
    CONDA_BACKUP_GFORTRAN=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gfortran
       CONDA_BACKUP_GPROF=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-gprof
         CONDA_BACKUP_GXX=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-g++
        CONDA_BACKUP_HOST=x86_64-conda-linux-gnu
          CONDA_BACKUP_LD=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-ld
     CONDA_BACKUP_LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,
                          --disable-new-dtags -Wl,--gc-sections
                          -Wl,-rpath,/drives/ssd1/manuel/miniconda3/envs/r4-base/lib -Wl,-rpath-
                          link,/drives/ssd1/manuel/miniconda3/envs/r4-base/lib
                          -L/drives/ssd1/manuel/miniconda3/envs/r4-base/lib
     CONDA_BACKUP_LD_GOLD=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-ld.gold
          CONDA_BACKUP_NM=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-nm
     CONDA_BACKUP_OBJCOPY=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-objcopy
     CONDA_BACKUP_OBJDUMP=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-objdump
      CONDA_BACKUP_RANLIB=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-ranlib
     CONDA_BACKUP_READELF=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-readelf
        CONDA_BACKUP_SIZE=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-size
     CONDA_BACKUP_STRINGS=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-strings
       CONDA_BACKUP_STRIP=/drives/ssd1/manuel/miniconda3/envs/r4-base/bin/x86_64-conda-linux-
                          gnu-strip
 CONDA_BACKUP_build_alias=x86_64-conda-linux-gnu
  CONDA_BACKUP_host_alias=x86_64-conda-linux-gnu
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/drives/ssd1/manuel/miniconda3/bin/conda
             CONDA_PREFIX=/drives/ssd1/manuel/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/drives/ssd1/manuel/miniconda3/bin/python
               CONDA_ROOT=/drives/ssd1/manuel/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/drives/ssd1/manuel/miniconda3/lib/server
                     PATH=/drives/ssd1/manuel/miniconda3/bin:/drives/ssd1/manuel/miniconda3/bin:
                          /drives/ssd1/manuel/miniconda3/envs/gapfilling/bin:/drives/ssd1/manuel
                          /miniconda3/envs/py27/bin:/home/zoo/zool2528/meme/bin:/home/zoo/zool25
                          28/meme/libexec/meme-5.4.1:/drives/ssd1/manuel/miniconda3/condabin:/us
                          r/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/
                          usr/local/games:/snap/bin:/drives/raid/AboobakerLab/software/bedtools2
                          /bin:/home/zoo/zool2528/.local/bin:/drives/raid/AboobakerLab/software/
                          ViennaRNA-2.4.18/src/bin:/drives/raid/AboobakerLab/software/ncbi-blast
                          -2.12.0+/bin:/drives/raid/AboobakerLab/software/bedops/bin:/drives/rai
                          d/AboobakerLab/software/SalmonTE:/drives/raid/AboobakerLab/software/sa
                          lmon-1.5.2_linux_x86_64/bin:/drives/raid/AboobakerLab/software/SalmonT
                          E/salmon/darwin/lib:/drives/raid/AboobakerLab/software/STAR-2.7.9a/bin
                          /Linux_x86_64:/drives/raid/AboobakerLab/software/STAR-2.7.9a/bin/Linux
                          _x86_64:/drives/raid/AboobakerLab/software/canu-2.2/bin:/drives/raid/A
                          boobakerLab/software/LR_Gapcloser/src:/drives/raid/AboobakerLab/softwa
                          re/LTR_FINDER_parallel/bin/LTR_FINDER.x86_64-1.0.7:/drives/raid/Abooba
                          kerLab/software/LTR_FINDER_parallel:/drives/raid/AboobakerLab/software
                          /seqtk:/drives/raid/AboobakerLab/software/standard-RAxML:/drives/raid/
                          AboobakerLab/software/quast:/drives/raid/AboobakerLab/software/gapless
                          :/drives/raid/AboobakerLab/software/hisat2/
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /drives/ssd1/manuel/miniconda3
            shell level : 1
       user config file : /home/zoo/zool2528/.condarc
 populated config files : /home/zoo/zool2528/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /drives/ssd1/manuel/miniconda3  (writable)
      conda av data dir : /drives/ssd1/manuel/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /drives/ssd1/manuel/miniconda3/pkgs
                          /home/zoo/zool2528/.conda/pkgs
       envs directories : /drives/ssd1/manuel/miniconda3/envs
                          /home/zoo/zool2528/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.5 Linux/5.15.0-52-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1792830678:1792800513
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

```

**Comment by ctsa** [comment]
Hi @Mjaraespejo , The python method has just been updated with a new compiled binary v2.1.0 release today to help better manage these package and conda issues:

https://github.com/PacificBiosciences/pb-CpG-tools/releases/latest

If you're still interested, can you give this a try instead?

**Comment by ctsa** [comment]
Closing as no longer applicable. Please open a new issue if you're having any trouble with v2.
