### ISSUE TITLE
 file has no sequences defined (mode='rb') - is it SAM/BAM format?

### ISSUE THREAD

**Issue by jdakota1305** [PacificBiosciences/pb-CpG-tools#6]
Hi All,

Excited to use this, but am running into issues when supplying an output from primrose to the CpG tool. I had no issue generating the bam file and index from primrose, but it doesn't seem to be working when I pass it to the the CpG tool. I have attached the log as well. Thanks in advance! 

[m5c.output-aligned_bam_to_cpg_scores.log](https://github.com/PacificBiosciences/pb-CpG-tools/files/8564203/m5c.output-aligned_bam_to_cpg_scores.log)

Chunking regions for multiprocessing.
Traceback (most recent call last):
  File "/fh/fast/johnston_c/bamsieve/jd-m4c/a95dc47b-b631-46e8-4dcb-e15857563cf3/aligned_bam_to_cpg_scores.py", line 981, in <module>
    main()
  File "/fh/fast/johnston_c/bamsieve/jd-m4c/a95dc47b-b631-46e8-4dcb-e15857563cf3/aligned_bam_to_cpg_scores.py", line 966, in main
    regions_to_process = get_regions_to_process(args.bam, args.fasta, args.chunksize, args.modsites,
  File "/fh/fast/johnston_c/bamsieve/jd-m4c/a95dc47b-b631-46e8-4dcb-e15857563cf3/aligned_bam_to_cpg_scores.py", line 138, in get_regions_to_process
    bamIn = pysam.AlignmentFile(input_bam, 'rb')
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 1000, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False

**Comment by rhallPB** [comment]
The pileup tool requires an aligned bam, it does not carry out the actual alignment. The results from primrose should be aligned to the reference with pbmm2 before calculation of the pileup.
