### ISSUE TITLE
Exception in thread Thread-4

### ISSUE THREAD

**Issue by yuntwang** [PacificBiosciences/pb-CpG-tools#9]
Hi.

Use this tool to analyze test data( https://downloads.pacbcloud.com/public/dataset/HG002-CpG-methylation-202202/),
The command is as follows:
**source anaconda3/bin/activate cpg
python aligned_bam_to_cpg_scores.py -b HG002.GRCh38.haplotagged.bam -o HG002 -p model -d pb-CpG-tools-1.0.0/pileup_calling_model/ -m denovo --threads 48 -f GCA_000001405.15_GRCh38_no_alt_analysis_set.fna**

**After running for about a few minutes, the error message is as follows:**
Chunking regions for multiprocessing.
Running multiprocessing on 6,362 chunks.
  0%|          | 0/6362 [00:19<?, ?it/s]Exception in thread Thread-4:
  0%|          | 0/6362 [00:51<?, ?it/s]Traceback (most recent call last):
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/threading.py", line 973, in _bootstrap_inner

    self.run()
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/concurrent/futures/process.py", line 320, in run
    self.terminate_broken(cause)
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/concurrent/futures/process.py", line 455, in terminate_broken
    work_item.future.set_exception(bpe)
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/concurrent/futures/_base.py", line 549, in set_exception
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
concurrent.futures._base.InvalidStateError: CANCELLED: <Future at 0x7f464ae4e670 state=cancelled>
Traceback (most recent call last):
  File "/share/nas1/wangyt/software/pb-CpG-tools-1.0.0/aligned_bam_to_cpg_scores.py", line 958, in <module>
    main()
  File "/share/nas1/wangyt/software/pb-CpG-tools-1.0.0/aligned_bam_to_cpg_scores.py", line 947, in main
    bed_results = run_all_pileup_processing(regions_to_process, args.threads)
  File "/share/nas1/wangyt/software/pb-CpG-tools-1.0.0/aligned_bam_to_cpg_scores.py", line 735, in run_all_pileup_processing
    bed_results = process_map(run_process_region, regions_to_process, max_workers=threads, miniters=threads, chunksize=1, smoothing=0)
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 130, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/share/nas1/wangyt/software/anaconda3/envs/cpg/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2022-05-11 13:53:53.287696: F tensorflow/core/platform/default/env.cc:73] Check failed: ret == 0 (11 vs. 0)Thread tf_Compute creation via pthread_create() failed.
2022-05-11 13:53:53.558040: F tensorflow/core/platform/default/env.cc:73] Check failed: ret == 0 (11 vs. 0)Thread tf_Compute creation via pthread_create() failed.

Look forward to your reply!

**Comment by rashidalabri** [comment]
I was literally just about to post an issue on this. Great odds! I'm also having the same issue with the tool. At least on my end, at least one thread exceeds the memory I have available for it (12 GB/thread, 192 GB for 16 threads) and the job scheduler kills the process.

**Comment by yuntwang** [comment]
On this server, my maximum CPU and memory are：64 and 757.4Gb.

Based on this, do you have any suggestions?

I see your performance in the text：
![image](https://user-images.githubusercontent.com/27258713/167780892-930dd1af-f708-498f-9422-6035e839750b.png)

**Comment by dportik** [comment]
Hi @yuntwang and @rashidalabri,

A spike in coverage in some portions of the genome can cause higher memory requirements for some regions. This effect can be magnified if the size of the region/chunk is relatively long. One potential solution is to reduce the length of each region/chunk using the following argument:

```
-s, --chunksize       INT     Break reference regions into chunks of this size for parallel 
                                processing. [500000]
```

You can try reducing this to `-s 250000` or `-s 100000`. It will reduce memory requirements per region/chunk. The tradeoff is that it will increase number of regions/chunks to process and affect the runtime proportionally.

Please try this and let me know if the issue persists.

**Comment by rashidalabri** [comment]
Hi @dportik, I appreciate the quick response. I ran the tool again with `-s 100000` but the issue still persists. For reference, the file I'm analyzing is ~50x coverage and I'm using 16 threads with 192GB of memory (so 12GB per thread). Would you recommend I decrease `-s` even more?

**Comment by yuntwang** [comment]
Hi @dporitik 
sorry, the same problem arises.
different combinations of -- threads and -- chunksize are not OK

Logically, I have a lot of resources and should not have this problem(On this server, my maximum CPU and memory are：64 and 757.4Gb ).

**Comment by dportik** [comment]
Hi @rashidalabri and @yuntwang,
I will try to track down a higher coverage dataset and test it with our current release.

In the meantime, you could also try reducing the number of threads (e.g., test if total memory available is exceeded across all threads).

**Comment by rashidalabri** [comment]
Hi @dportik,
I reran the tool using just 4 threads/192GB of memory, and encountered the same issue. The BAM file is about ~250 GB. I'm thinking there might be a memory leak somewhere? But I don't know for sure. I appreciate your help with this.

**Comment by dportik** [comment]
Hi @rashidalabri and @yuntwang,
Is there any chance you can post a log file from one of the runs that crashed? This can assist us in determining the issue.

**Comment by yuntwang** [comment]
@dportik 
Hi.  I tried several times, but none of them reproduced the above error. It feels strange

**Comment by ctsa** [comment]
Hi @yuntwang and @rashidalabri , I've created a branch with improved exception reporting to help us make some progress on this issue. It is not clear from your reports if this is always an issue with memory exhaustion or if other factors could be involved, so the improved errors might help us work through the reported problems more quickly.

Could you retry your cases with the following branch?

https://github.com/PacificBiosciences/pb-CpG-tools/tree/better_errors

**Comment by dportik** [comment]
Hi @yuntwang and @rashidalabri,
Any update on this? Have you tried the updated script? If there are no updates I will close this issue.
